language: node_js
node_js:
- 4.4.7
install:
- npm install
after_success:
- bash deploy.sh
env:
  global:
  - secure: Uahbxzd8FIlaNTBTno8WvWe1NnHSQzSOWTF2wDDYAeIw4p1EtdntKD+nYHZqEXG27o7t5Z+TuN1uYwodYbcv18IA/NA7o+1aJm62gyX4bWyODOUDmdENc+EnURr9TH6nOU4Kqit0SLUFv48gnKxzBakvJhfiCxohd1LNid/sjVifThAI0gXYz/whmNOVkKxSZyXd509Lct/yVT8Li2VEqDBo7BcYfvuAHF5PQBiqRJ12uWKQPLEGX5bMdH68YeSRikvNlkXY7b0lPRGvh0y8+y4Ex3PFwtlLdxXn6xTWONueoin51kOj5N4DeOuRZArhD5rvGbCxiqJjokRgoeIqr9F0VdGvHfWei3Vd4F+Ve4kOW4efO03Frixh8nfl269jX7as9IT51ghFghzwMigeRzGBL/JB3/E8Doos5NgXPYDQlRFg9KzpDxNJMEdoN4Zq4z8axilmyqHaMzXevYMae3jtIopCNQ6O7FgkCXeyYQf3W1fBpvAmFE/LfZXGoXcT4Wx863bYjbtEaqEIXalkwrBbYtUfcG5gCCUfLX6vL8knM6JhHP8chhAxlGOWf0HnDIIBksIP2Ld7cgUO8w6PCXQ+wkEYjki7S58GB/RzNWcEGve0hIROBRAmE8UwujCDw3jkfsotVU2uNUZz5f62YIw/6BBU8893huwKzQvIALs=
