language: node_js
node_js:
- 4.4.7
install:
- npm install
after_success:
- bash deploy.sh
env:
  global:
    secure: Gu6mFo57qTaCUxMC1Ws3Scf/bkha7vvCGAgn8zwUpQ1bttvmBPg+hbxlu3VS5EaUYeg4nUvb0xjx5teYJc/zJXtTOHmixulvbpiONuGGlyC3oGsQUxo5Z7HhoSoNdB0+jC84VRrZJu38mp+X6oNxwBdRmTKiENT5FunyNvIRbWF+CMuNivAbI4J5OnhVOOhVOCaJYfAxpt/sGdI+ewTbJUjzHTLi4CAqC5l2MRn+0q082K7eNNoXanmCylmfWDnPgMdMRw/kzRqNNfvwYrbe8UjkV3VfH1WY+K/P8gGVmC+jRaNiGnxQDAfbSnqfo5z0eE98PuOe8lM4IjhBfAuqV4PGs/6dzfVTuLZMK1VsLEoBqyoQVFbhd7+JCOjFWfNM6J7W5LYVhenKazz9y7VqKDd8dhwBETmFRRwH5TEJDa9RfKhiG9EARAv3mHyffJpK9vTCjd5vximY8GCVESOmcaDhzl5XdIaZKoH4qb7yLWzGZt9XLHpKiIWEAFEofXAsF73T5DgrIbCUDLvH2lQpwKfNZUcgUAQMvszJP4UmR4TvfrFTLOVkrST++vN+1V0moyrMax4VM1QiyBisN1hxZXksR3h/i4S8CNHsd35KxpR9UnKgqKPkUaDvb17Zh+vgcmKmbTB3JtK2/YkO1GR56Qf2T45MOsiRkE89PqmedAw=
